"""SourceData protocol."""

from typing import Protocol, runtime_checkable

from collectors_sdk._core.base_collector.models.data import OAEVData, TraceData


@runtime_checkable
class SourceDataProtocol(Protocol):
    def to_oaev_data(self) -> OAEVData: ...
    def to_traces_data(self) -> TraceData: ...
    def is_prevented(self) -> bool: ...
    def is_detected(self) -> bool: ...
    def __str__(self) -> str: ...
