version: "3"
services:
  collector-template:
    image: openaev/collector-template:rolling
    environment:
      - OPENAEV_URL=http://localhost
      - OPENAEV_TOKEN=ChangeMe
      - OPENAEV_TENANT_ID=ChangeMe
      - COLLECTOR_ID=ChangeMe
      - SOURCE_KEY=ChangeMe
    restart: always
