FROM registry.access.redhat.com/ubi9/ubi-minimal as base

RUN set -eux; \
    microdnf -y --setopt=install_weak_deps=0 install python3.14; \
    microdnf clean all;


FROM base as builder

RUN set -eux; \
    microdnf -y --setopt=install_weak_deps=0 install python3.14-pip; \
    pip3.14 install poetry==2.3.2; \
    microdnf -y remove python3.14-pip; \
    microdnf clean all;

WORKDIR /collector
COPY ./ ./
RUN set -eux; \
    poetry build


FROM base as runner

# Declare the build argument
ARG COLLECTOR_CMD
ENV COLLECTOR_CMD=${COLLECTOR_CMD}
ARG PYOAEV_GIT_REF_OVERRIDE=""

WORKDIR /collector
COPY --from=builder /collector/ ./

RUN set -eux; \
    microdnf -y --setopt=install_weak_deps=0 install python3.14-pip; \
    (cd dist && pip3.14 install --no-cache-dir "$(ls *.whl)"); \
    if [ -n "${PYOAEV_GIT_REF_OVERRIDE}" ] ; then \
        echo "Forcing specific version of client-python"; \
        microdnf -y --setopt=install_weak_deps=0 install git-core; \
        pip3.14 uninstall -y pyoaev; \
        pip3.14 install git+https://github.com/OpenAEV-Platform/client-python@${PYOAEV_GIT_REF_OVERRIDE}; \
        microdnf -y remove git-core; \
    fi; \
    microdnf -y remove python3.14-pip; \
    microdnf clean all;

CMD python3.14 -m ${COLLECTOR_CMD}
