version: "3"
services:
  collector-microsoft-defender-o365:
    image: openaev/collector-microsoft-defender-o365:rolling
    environment:
      - OPENAEV_URL=http://localhost
      - OPENAEV_TOKEN=ChangeMe
      - OPENAEV_TENANT_ID=ChangeMe
      - COLLECTOR_ID=ChangeMe
      - SOURCE_TENANT_ID=ChangeMe
      - SOURCE_CLIENT_ID=ChangeMe
      - SOURCE_CLIENT_SECRET=ChangeMe

      - OPENAEV_URL=${OPENAEV_URL}
      - OPENAEV_TOKEN=${OPENAEV_TOKEN}
      # only required for multi-tenancy (Enterprise Edition), keep commented otherwise
      # - OPENAEV_TENANT_ID=${OPENAEV_TENANT_ID}
      - COLLECTOR_ID=${COLLECTOR_ID}
      - COLLECTOR_NAME=${COLLECTOR_NAME:-"Microsoft Defender o365"}
      - COLLECTOR_LOG_LEVEL=${COLLECTOR_LOG_LEVEL:-error}
      - COLLECTOR_PERIOD=${COLLECTOR_PERIOD:-PT2M}
      - COLLECTOR_PLATFORM=${COLLECTOR_PLATFORM:-EDR}
      - SOURCE_TENANT_ID=${SOURCE_TENANT_ID}
      - SOURCE_CLIENT_ID=${SOURCE_CLIENT_ID}
      # - SOURCE_USE_CERTIFICATE_AUTH=${SOURCE_USE_CERTIFICATE_AUTH}
      - SOURCE_CLIENT_SECRET=${SOURCE_CLIENT_SECRET}
      # - SOURCE_CLIENT_CERT_DATA=${SOURCE_CLIENT_CERT_DATA}
      # - SOURCE_CLIENT_CERT_THUMBPRINT=${SOURCE_CLIENT_CERT_THUMBPRINT}
      # - SOURCE_CLIENT_CERT_PASSPHRASE=${SOURCE_CLIENT_CERT_PASSPHRASE}
      # - SOURCE_BASE_URL=${SOURCE_BASE_URL:-https://graph.microsoft.com/v1.0}
      # - SOURCE_FILTER_SERVICE_SOURCE=${SOURCE_FILTER_SERVICE_SOURCE:-microsoftDefenderForOffice365}
      # - SOURCE_RATE_LIMIT_REQUESTS_PER_MINUTE=${SOURCE_RATE_LIMIT_REQUESTS_PER_MINUTE:-150}
      # - SOURCE_MAX_FETCH_RETRIES=${SOURCE_MAX_FETCH_RETRIES:-5}
    restart: always
