version: '3'
services:
  collector-aws-resources:
    image: openaev/collector-aws-resources:latest
    environment:
      - OPENAEV_URL=${OPENAEV_URL}
      - OPENAEV_TOKEN=${OPENAEV_TOKEN}
      # only required for multi-tenancy (Enterprise Edition), keep commented otherwise
      # - OPENAEV_TENANT_ID=${OPENAEV_TENANT_ID}
      - COLLECTOR_ID=${COLLECTOR_ID}
      - COLLECTOR_NAME=${COLLECTOR_NAME}
      - COLLECTOR_PERIOD=${COLLECTOR_PERIOD}
      - COLLECTOR_LOG_LEVEL=${COLLECTOR_LOG_LEVEL}
      - COLLECTOR_AWS_AUTH_TYPE=${AWS_AUTH_TYPE:-credential_provider_chain}
      - COLLECTOR_AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - COLLECTOR_AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - COLLECTOR_AWS_SESSION_TOKEN=${AWS_SESSION_TOKEN}
      - COLLECTOR_AWS_ASSUME_ROLE_ARN=${AWS_ASSUME_ROLE_ARN}
      - COLLECTOR_AWS_REGIONS=${AWS_REGIONS}
      # only required when COLLECTOR_AWS_AUTH_TYPE=roles_anywhere
      - COLLECTOR_AWS_ROLES_ANYWHERE_TRUST_ANCHOR_ARN=${AWS_ROLES_ANYWHERE_TRUST_ANCHOR_ARN}
      - COLLECTOR_AWS_ROLES_ANYWHERE_PROFILE_ARN=${AWS_ROLES_ANYWHERE_PROFILE_ARN}
      - COLLECTOR_AWS_ROLES_ANYWHERE_ROLE_ARN=${AWS_ROLES_ANYWHERE_ROLE_ARN}
      - COLLECTOR_AWS_ROLES_ANYWHERE_CERTIFICATE=${AWS_ROLES_ANYWHERE_CERTIFICATE}
      - COLLECTOR_AWS_ROLES_ANYWHERE_PRIVATE_KEY=${AWS_ROLES_ANYWHERE_PRIVATE_KEY}
      - COLLECTOR_AWS_ROLES_ANYWHERE_CERTIFICATE_CHAIN=${AWS_ROLES_ANYWHERE_CERTIFICATE_CHAIN}
      - COLLECTOR_AWS_ROLES_ANYWHERE_PRIVATE_KEY_PASSPHRASE=${AWS_ROLES_ANYWHERE_PRIVATE_KEY_PASSPHRASE}
      - COLLECTOR_AWS_ROLES_ANYWHERE_REGION=${AWS_ROLES_ANYWHERE_REGION}
      - COLLECTOR_AWS_ROLES_ANYWHERE_SESSION_DURATION=${AWS_ROLES_ANYWHERE_SESSION_DURATION:-3600}
    restart: always
