services:
  collector-xtm-one:
    image: openaev/collector-xtm-one:latest
    environment:
      - OPENAEV_URL=${OPENAEV_URL}
      - OPENAEV_TOKEN=${OPENAEV_TOKEN}
      - OPENAEV_TENANT_ID=${OPENAEV_TENANT_ID}
      - COLLECTOR_ID=${COLLECTOR_ID}
      - COLLECTOR_NAME=${COLLECTOR_NAME:-"XTM One"}
      - COLLECTOR_LOG_LEVEL=${COLLECTOR_LOG_LEVEL:-warn}
      - COLLECTOR_PERIOD=${COLLECTOR_PERIOD:-PT1H}
      - COLLECTOR_XTM_ONE_URL=${COLLECTOR_XTM_ONE_URL}
      - COLLECTOR_XTM_ONE_TOKEN=${COLLECTOR_XTM_ONE_TOKEN}
      - COLLECTOR_XTM_ONE_API_KEY_VARIABLE=${COLLECTOR_XTM_ONE_API_KEY_VARIABLE:-XTM_ONE_API_KEY}
      - COLLECTOR_INCLUDE_BARE_MODELS=${COLLECTOR_INCLUDE_BARE_MODELS:-false}
      - COLLECTOR_AGENT_TAGS=${COLLECTOR_AGENT_TAGS:-}
    restart: unless-stopped
