services:
  collector-openbas:
    image: openbas/collector-openbas:latest
    environment:
      - OPENBAS_URL=${OPENBAS_URL}
      - OPENBAS_TOKEN=${OPENBAS_TOKEN}
      - COLLECTOR_ID=${COLLECTOR_ID}
      - COLLECTOR_NAME=${COLLECTOR_NAME}
      - COLLECTOR_LOG_LEVEL=${COLLECTOR_LOG_LEVEL}
      - COLLECTOR_PERIOD=${COLLECTOR_PERIOD}
      - COLLECTOR_TYPE=${COLLECTOR_TYPE}
      - OPENBAS_URL_PREFIX=${OPENBAS_URL_PREFIX}
      - OPENBAS_IMPORT_ONLY_NATIVE=${OPENBAS_IMPORT_ONLY_NATIVE}
    restart: always
