services:
  collector-microsoft-defender:
    image: openaev/collector-microsoft-defender:latest
    environment:
      - OPENAEV_URL=${OPENAEV_URL}
      - OPENAEV_TOKEN=${OPENAEV_TOKEN}
      # only required for multi-tenancy (Enterprise Edition), keep commented otherwise
      # - OPENAEV_TENANT_ID=${OPENAEV_TENANT_ID}
      - COLLECTOR_ID=${COLLECTOR_ID}
      - COLLECTOR_NAME=${COLLECTOR_NAME:-"Microsoft Defender"}
      - COLLECTOR_LOG_LEVEL=${COLLECTOR_LOG_LEVEL:-error}
      - COLLECTOR_PERIOD=${COLLECTOR_PERIOD:-PT1M}
      - COLLECTOR_PLATFORM=${COLLECTOR_PLATFORM:-EDR}
      - SOURCE_TENANT_ID=${SOURCE_TENANT_ID}
      - SOURCE_CLIENT_ID=${SOURCE_CLIENT_ID}
      # - SOURCE_USE_CERTIFICATE_AUTH=${SOURCE_USE_CERTIFICATE_AUTH}
      - SOURCE_CLIENT_SECRET=${SOURCE_CLIENT_SECRET}
      # - SOURCE_CLIENT_CERT_DATA=${SOURCE_CLIENT_CERT_DATA}
      # - SOURCE_CLIENT_CERT_THUMBPRINT=${SOURCE_CLIENT_CERT_THUMBPRINT}
      # - SOURCE_BASE_URL=${SOURCE_BASE_URL}
      # - SOURCE_FILTER_SERVICE_SOURCE=${SOURCE_FILTER_SERVICE_SOURCE}
      # - SOURCE_RATE_LIMIT_REQUESTS_PER_MINUTE=${SOURCE_RATE_LIMIT_REQUESTS_PER_MINUTE}
      # - SOURCE_MAX_FETCH_RETRIES=${SOURCE_MAX_FETCH_RETRIES}
    restart: unless-stopped
